pipeline{
    agent any
    tools{
        maven 'Maven'
    }
    stages{

        stage('Checkout'){
            steps{
                echo 'Checking out...'
                git 'https://github.com/bharathreddy20031910/Java-example.git' , branch: 'main'

                }
        }
        stage('Change Dir'){
                sh 'cd Java-simplep'
        }
        stage('Build'){
            steps{
                echo 'Building...'
                sh 'mvn clean package'
            }
        }
        stage('Test'){
            steps{
                echo 'Testing...'
                sh 'mvn test'
            }
        }
        stage('Deploy'){
            steps{
                echo 'Deploying...'
            }
        }
    }
}